      # Step 1: List Existing Tags
      - name: List existing tags
        run: |
          git fetch --tags
          git tag -l

      # Step 2: Delete Existing Release
      - name: Check and Delete Existing Release
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const tagName = 'v1.01.0001'; // Adjust to the exact tag format
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const existingRelease = releases.data.find(release => release.tag_name === tagName);
            if (existingRelease) {
              console.log(`Release with tag ${tagName} exists. Deleting...`);
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: existingRelease.id
              });
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tagName}`
              });
              console.log(`Deleted release with tag ${tagName}.`);
            } else {
              console.log(`No release found with tag ${tagName}.`);
            }
