name: Android CI

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository with all history and tags
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0  # Fetch all history including tags

      # 2. Cache Gradle packages
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 3. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Set up Android SDK and NDK
      - name: Set up Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '33.0.0'
          ndk-version: '27.0.11718014'
          distribution-type: 'sdk'
          build-tools: '33.0.0'

      # 5. Build with Gradle
      - name: Build with Gradle
        run: ./gradlew assembleRelease --warning-mode all

      # 6. Create and Push Tag
      - name: Create and Push Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG="v1.01.$(date +%Y%m%d%H%M%S)"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
        id: tag

      # 7. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: io.esper.android.files.apk
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 10

      # Debug: List artifacts in the build directory
      - name: List APK in build directory
        run: ls -la app/build/outputs/apk/release/
