name: Create Release

on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

permissions:
  contents: write   # Grants permission to create and modify releases

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository with all history and tags
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history including tags

      # 2. Extract version number from the latest tag
      - name: Extract version number from tag
        id: extract_version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          VERSION=${TAG#v}
          echo "versionName=${VERSION}" >> $GITHUB_ENV
          echo "Extracted versionName: $VERSION"

      # 3. List all available artifacts
      - name: List all available artifacts
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts

      # 4. Download APK Artifact
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: io.esper.android.files.apk
          path: ./release-apk

      # 5. List downloaded APKs for verification
      - name: List downloaded APKs
        run: ls -la ./release-apk/

      # 6. Verify Downloaded APK Exists
      - name: Verify Downloaded APK Exists
        run: |
          APK_PATH="./release-apk/io.esper.android.files.apk"
          if [ -f "$APK_PATH" ]; then
            echo "APK exists: $APK_PATH"
          else
            echo "Error: APK not found at $APK_PATH"
            exit 1
          fi

      # 7. Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.versionName }}"  # Use the version name extracted
          release_name: "Release v${{ env.versionName }}"
          body: |
            Changes in this Release:
            - ${{ github.event.workflow_run.head_commit.message }}
          draft: false
          prerelease: false

      # 8. Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-apk/io.esper.android.files.apk
          asset_name: io.esper.android.files.apk
          asset_content_type: application/vnd.android.package-archive
