name: Create Release

on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed

permissions:
  contents: write   # Grants permission to create and modify releases

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository (optional but recommended)
      - name: Check out repository
        uses: actions/checkout@v3

      # 2. Download the APK artifact from the build workflow
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: io.esper.android.files_v${{ substring(github.ref_name, 1, 999) }}.apk  # Stripping 'v' using substring
          path: ./release-apk

      # 3. Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ github.ref_name }}"  # e.g., v1.01.0002
          release_name: "Release ${{ github.ref_name }}"
          body: |
            Changes in this Release:
            - ${{ github.event.workflow_run.head_commit.message }}
          draft: false
          prerelease: false

      # 4. Upload Release APK
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-apk/io.esper.android.files_v${{ substring(github.ref_name, 1, 999) }}.apk
          asset_name: io.esper.android.files_v${{ substring(github.ref_name, 1, 999) }}.apk
          asset_content_type: application/vnd.android.package-archive
